repos:
  - repo: https://github.com/comecord/husky
    rev: v1.0.4
    hooks:
      - id: increment-patch-version
        name: Increment Patch Version
        entry: go run github.com/comecord/husky@v1.0.4 patch
        language: golang
        pass_filenames: false
        always_run: true

