repos:
  - repo: https://github.com/icehuntmen/pre-commit-golang
    rev: cd54b428907edd1dc3e835bf6d25255a3c30b3fb
    hooks:
      - id: go-fmt-import
      - id: go-vet
      - id: go-lint
      - id: go-version
      - id: go-unit-tests
      - id: gofumpt # requires github.com/mvdan/gofumpt
      - id: go-err-check # requires github.com/kisielk/errcheck
      - id: go-static-check # install https://staticcheck.io/docs/
      - id: golangci-lint # requires github.com/golangci/golangci-lint
        args: [--config=.github/linters/.golangci.yml] # optional
      - id: go-ruleguard # requires https://github.com/quasilyte/go-ruleguard
        args: [rules/rules.go] # required