repos:
  -   repo: local
      hooks:
        -   id: update-version
            name: go update version
            entry: bash -c 'update_version.sh'
            language: system
            files: VERSION