version: '3'
services:
  mongodb:
    image: mongo
    container_name: crmglonass-mongodb
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: demoglonass2024CRM
        MONGO_INITDB_DATABASE: demoglonass
        MONGO_USERNAME: admin
        MONGO_PASSWORD: demoglonass2024CRMadmin
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/mongox

  redis:
    image: redis:alpine
    command: redis-server --requirepass crmredis2024
    container_name: crmglonass-redis
    ports:
      - '6379:6379'
    volumes:
      - redisDB:/data
volumes:
  mongodb:
  redisDB:
