version: '3.9'
services:
  mongodb:
    image: mongo
    container_name: drivers-service-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: demoglonass2024CRM
      MONGO_INITDB_DATABASE: demoglonass
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro

  redis:
    image: redis:alpine
    command: redis-server --requirepass crmredis2024
    container_name: drivers-service-redis
    ports:
      - '6379:6379'
    volumes:
      - redisDB:/data
volumes:
  mongodb:
  redisDB:
