
server:
  timeZone: Europe/Moscow
  domain: localhost
  internalPort: 5100
  externalPort: 5100
  runMode: debug
smtp:
  emailFrom: notify@comecord.com
  smtpHost: smtp.comecord.com
  smtpPort: 587
  smtpUser: noreply@comecord.com
  smtpPass: <PASSWORD>
  smtpAuth: false
  smtpSecure: true
logger:
  filePath: ./logs/
  encoding: json
  level: debug
  logger: logrus
cors:
  allowOrigins: "*"
notify:
  telegramToken: 9876543210098765432109876543211111
  telegramChatId: -1234567890
mongox:
  host: localhost
  port: 27017
  database: demoglonass
  username: root
  password: demoglonass2024CRM
  authSource: admin
  replicaSet: r1shard
  readPreference: Primary
redis:
  host: localhost
  port: 6379
  password: crmredis2024
  db: 0
  dialTimeout: 5
  readTimeout: 5
  writeTimeout: 5
  poolSize: 10
  poolTimeout: 15
  idleCheckFrequency: 500
password:
  includeChars: true
  includeDigits: true
  minLength: 6
  maxLength: 64
  includeUppercase: true
  includeLowercase: true
otp:
  expireTime: 120
  digits: 6
  limiter: 100
jwt:
  secret: "mySecretKey"
  refreshSecret: "mySecretKey"
  accessTokenExpireDuration: 60
  refreshTokenExpireDuration: 3600