definitions:
  components.BaseHttpResponse:
    properties:
      error: {}
      result: {}
      resultCode:
        $ref: '#/definitions/components.ResultCode'
      success:
        type: boolean
      validationErrors:
        items:
          $ref: '#/definitions/validations.ValidationError'
        type: array
    type: object
  components.ResultCode:
    enum:
    - 0
    - 40001
    - 40101
    - 40301
    - 40401
    - 42901
    - 442902
    - 50001
    - 50002
    type: integer
    x-enum-varnames:
    - Success
    - ValidationError
    - AuthError
    - ForbiddenError
    - NotFoundError
    - LimiterError
    - OtpLimiterError
    - CustomRecovery
    - InternalError
  dto.CreateVehicleRequest:
    properties:
      location:
        type: string
      model:
        type: string
      name:
        type: string
      price:
        type: integer
      year:
        type: integer
    type: object
  dto.DBVehicleDTO:
    properties:
      created_at:
        type: string
      id:
        type: string
      location:
        type: string
      model:
        type: string
      name:
        type: string
      price:
        type: integer
      updated_at:
        type: string
      year:
        type: integer
    type: object
  validations.ValidationError:
    properties:
      message:
        type: string
      property:
        type: string
      tag:
        type: string
      value:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
info:
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /api/v1/health/:
    get:
      consumes:
      - application/json
      description: Health Check
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/components.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/components.BaseHttpResponse'
      summary: Health Check
      tags:
      - Health Check
  /v1/vehicles/:
    post:
      consumes:
      - application/json
      description: Create a vehicle
      parameters:
      - description: Create a vehicle model
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateVehicleRequest'
      responses:
        "201":
          description: Created response
          schema:
            allOf:
            - $ref: '#/definitions/components.BaseHttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/dto.DBVehicleDTO'
              type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/components.BaseHttpResponse'
      security:
      - AuthBearer: []
      summary: Create a vehicle
      tags:
      - Vehicles
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
